spring:
  application:
    name: transport-rental
  security:
    csrfEnabled: ${ENABLE_CSRF_TOKEN:true}
  datasource:
    url: jdbc:postgresql://localhost:5432/simbirgo?currentSchema=public&user=postgres&password=postgres
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:10}
      minimum-idle: ${DB_MIN_POOL_SIZE:1}
      idle-timeout: ${DB_IDLE_TIMEOUT_MS:60000}
      connection-timeout: ${DB_CONNECTION_TIMEOUT_MS:90000}
      max-lifetime: ${DB_MAX_CONN_LIFETIME_MS:300000}
      pool-name: MasterCP-1
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
  liquibase:
    change-log: classpath:/liquibase/master-changelog.xml

logging:
  level:
    root: INFO
    com:
      zaxxer:
        hikari: INFO
    liquibase: INFO
    net:
      sf:
        jasperreports: INFO
    org:
      springframework:
        web: INFO
        security: INFO
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
              BasicExtractor: TRACE
        SQL: DEBUG